import { createJourneyModel as createCoreJourneyModel } from "./model";
import { scenarioPersistenceAdapter } from "./scenario-persistence";
import type { JourneyModel } from "./model";

/**
 * Creates the public Journey Model with Scenario persistence installed.
 *
 * @returns A framework-independent model exposing compilation, generation, simulation, routing,
 * and transactional Scenario persistence operations.
 */
export function createJourneyModel(): JourneyModel {
  return createCoreJourneyModel(scenarioPersistenceAdapter);
}

export {
  kilograms,
  meters,
  metersCubedPerSecondSquared,
  metersPerSecond,
  metersPerSecondSquared,
  seconds,
  SPEED_OF_LIGHT,
  vector3,
} from "./quantities";
export type {
  GravitationalParameter,
  Kilograms,
  Meters,
  MetersPerSecond,
  MetersPerSecondSquared,
  PositionVector,
  Seconds,
  SIQuantity,
  SIUnit,
  SIValue,
  Vector3,
  VelocityVector,
} from "./quantities";
export {
  compileScenario,
  evaluateWorldlines,
  formatScenarioInspection,
  inspectScenario,
  inspectScenarioAtTime,
  stableId,
  applyScenarioOverrides,
  compareScenarioOverrides,
  revertScenarioOverride,
  createScenarioReference,
  createScenarioSeed,
} from "./model";
export type {
  CompiledGate,
  CompiledGateConnection,
  CompiledOrbitalAnchor,
  CompiledScenario,
  CompiledScenarioIndex,
  ReadonlyEntityIndex,
  CompiledShipProfile,
  CompiledSystem,
  CompileScenarioFailure,
  CompileScenarioResult,
  CompileScenarioSuccess,
  DomainEntityType,
  GateConnectionInput,
  GateConnectionInspection,
  GateInput,
  GateInspection,
  JourneyModel,
  OrbitalAnchorInput,
  OrbitalAnchorKind,
  ScenarioEntityCounts,
  ScenarioEpoch,
  ScenarioGenerationMetadata,
  ScenarioGenerationMetadataInput,
  ScenarioInput,
  ScenarioInspection,
  ScenarioReference,
  ScenarioReferenceInput,
  ScenarioSeed,
  ScenarioSeedInput,
  ScenarioSeedKind,
  SavedJourneyInput,
  ShipProfileInput,
  ShipProfileInspection,
  StableId,
  SystemInput,
  SystemInspection,
  ValidationIssue,
  ValidationIssueCode,
  CompiledKeplerianOrbit,
  CompiledOrbitalElements,
  GateWorldline,
  KeplerianOrbitInput,
  OrbitalAnchorWorldline,
  OrbitalElementsInput,
  ScenarioWorldlineFailure,
  ScenarioWorldlineResult,
  ScenarioWorldlineSuccess,
  ScenarioWorldlines,
  WorldlineIssue,
  WorldlineIssueCode,
  CompiledEntityProvenance,
  EntityProvenanceInput,
  ScenarioCanonicalClaim,
  ScenarioCanonicalClaimInput,
  ScenarioUncertainty,
} from "./model";
export {
  isSupportedClusterGeneratorVersion,
  isSupportedScenarioGeneratorVersion,
} from "./generator-versions";
export {
  CURRENT_SCENARIO_SCHEMA_VERSION,
  DEFAULT_SCENARIO_GENERATOR_VERSION,
  DEFAULT_SCENARIO_SEED,
  LEGACY_SCENARIO_SCHEMA_VERSION,
  SCENARIO_SCHEMA_VERSION,
  SUPPORTED_SCENARIO_GENERATOR_VERSIONS,
  SUPPORTED_SCENARIO_SCHEMA_VERSIONS,
  createScenarioExport,
  deserializeScenario,
  exportScenario,
  importScenario,
  migrateScenario,
  migrateScenarioDocument,
  serializeScenario,
} from "./scenario-persistence";
export type {
  ScenarioExportDocument,
  ScenarioExportGate,
  ScenarioExportGateConnection,
  ScenarioExportOptions,
  ScenarioExportOrbitalAnchor,
  ScenarioExportSource,
  ScenarioExportShipProfile,
  ScenarioExportSystem,
  ScenarioImportFailure,
  ScenarioImportResult,
  ScenarioImportSuccess,
  ScenarioMigrationFailure,
  ScenarioMigrationResult,
  ScenarioMigrationSuccess,
  ScenarioPersistenceIssue,
  ScenarioPersistenceIssueCode,
} from "./scenario-persistence";
export {
  compareCanonClaim,
  compareCanonicalClaim,
  conservativeBounds,
  conservativeUncertaintyWidth,
  createCanonDiscrepancy,
  createCitation,
  createDisplayPrecision,
  createPropertyMetadata,
  createProvenance,
  createScenarioOverrideLayer,
  derivedResult,
  displayPrecisionForClaim,
  exactBounds,
  exactClaim,
  formatDisplayValue,
  formatWithPrecision,
  generatedProvenance,
  novelProvenance,
  overrideProvenance,
  provisionalProvenance,
  qualitativeClaim,
  rangeClaim,
  selectNominal,
  supplementaryOfficialProvenance,
} from "./provenance";
export type {
  CanonDiscrepancy,
  CanonicalClaim,
  CanonicalIdentity,
  CanonicalIdentityInput,
  Citation,
  CitationAuthority,
  CitationInput,
  ConservativeBounds,
  ConservativeUncertaintyWidth,
  DerivedResult,
  DisplayPrecision,
  DisplayPrecisionInput,
  ExactCanonicalClaim,
  PropertyMetadata,
  PropertyMetadataInput,
  Provenance,
  ProvenanceInput,
  ProvenanceKind,
  QualitativeCanonicalClaim,
  RangeCanonicalClaim,
  RangeClaimOptions,
  SelectedNominal,
  ScenarioOverrideChange,
  ScenarioOverrideChangeInput,
  ScenarioOverrideLayer,
  ScenarioOverrideLayerInput,
  OverrideChangeComparison,
} from "./provenance";
export {
  INTERCEPT_MAX_SEARCH_SECONDS,
  INTERCEPT_POSITION_RESIDUAL_FACTOR,
  INTERCEPT_POSITION_RESIDUAL_TOLERANCE,
  INTERCEPT_TIME_RESIDUAL_TOLERANCE,
  INTERSTELLAR_CRUISE_SPEED,
  sampleJourney,
  sampleJourneyAt,
  simulateFixedGateCruise,
  simulateJourney,
  simulateMultiLegJourney,
  stepJourneyEvent,
} from "./simulation";
export { evaluateGateWorldline, evaluateScenarioWorldlines } from "./orbital";
export {
  IN_SYSTEM_TRANSFER_MAX_SEARCH_SECONDS,
  IN_SYSTEM_TRANSFER_POSITION_RESIDUAL_TOLERANCE,
  IN_SYSTEM_TRANSFER_TIME_RESIDUAL_TOLERANCE,
  IN_SYSTEM_TRANSFER_VELOCITY_RESIDUAL_TOLERANCE,
  sampleInSystemTransferAt,
  simulateInSystemTransfer,
} from "./in-system-transfer";
export {
  DEFAULT_ROUTE_PLANNING_MAX_ALTERNATIVES,
  DEFAULT_ROUTE_PLANNING_SEARCH_BUDGET,
  MAX_ROUTE_PLANNING_BUDGET,
  planJourney,
  planRoute,
} from "./route-planning";
export type {
  ExplicitRoutePlan,
  JourneyPlanningRequest,
  JourneyPlanningResult,
  JourneyRouteDwell,
  JourneyRoutePlan,
  RouteDwellSelection,
  RoutePlan,
  RoutePlanSummary,
  RoutePlanningHorizon,
  RouteProvenanceFilter,
  RouteSensitivity,
  RouteUncertaintySummary,
  StrategicDwell,
  StrategicDwellInsertion,
  RoutePlanningFailure,
  RoutePlanningOptimality,
  RoutePlanningRefinementQuality,
  RoutePlanningSearchBudget,
  RoutePlanningSearchStats,
  RoutePlanningIssue,
  RoutePlanningIssueCode,
  RoutePlanningOutcome,
  RoutePlanningRequest,
  RoutePlanningResult,
  RoutePlanningSuccess,
} from "./route-planning";
export type {
  InSystemTransferEvent,
  InSystemTransferEventKind,
  InSystemTransferIssue,
  InSystemTransferIssueCode,
  InSystemTransferPhase,
  InSystemTransferPhaseKind,
  InSystemTransferRequest,
  InSystemTransferSample,
  InSystemTransferSamplingModel,
  InSystemTransferSamplingPhase,
  InSystemTransferSamplingVector,
  InSystemTransferSimulationFailure,
  InSystemTransferSimulationResult,
  InSystemTransferSimulationSuccess,
  InSystemTransferTerminalResiduals,
  InSystemTransferTimeline,
} from "./in-system-transfer";
export type {
  ArrivalIntercept,
  FixedGateCruiseRequest,
  InterstellarCruiseRequest,
  JourneyClockBounds,
  JourneyClockReading,
  JourneyEventStepDirection,
  JourneyCruiseLeg,
  JourneyDwellLeg,
  JourneyDwellTimeline,
  JourneyEventKind,
  JourneyLeg,
  JourneyLegKind,
  JourneyPhase,
  JourneyPhaseBounds,
  JourneyPhaseKind,
  JourneyRequest,
  JourneySample,
  JourneySampleFailure,
  JourneySamplePhaseDetails,
  JourneySampleProvenance,
  JourneySampleResult,
  JourneySampleSuccess,
  JourneySampleUncertainty,
  JourneySampleView,
  JourneySimulationFailure,
  JourneySimulationRequest,
  JourneySimulationResult,
  JourneySimulationSuccess,
  JourneyTimeline,
  JourneyTimelineEvent,
  JourneyTransferLeg,
  MultiLegJourneyLeg,
  MultiLegJourneyPhase,
  MultiLegJourneyRequest,
  MultiLegJourneySimulationFailure,
  MultiLegJourneySimulationResult,
  MultiLegJourneySimulationSuccess,
  MultiLegJourneyTimeline,
  MultiLegJourneyTimelineEvent,
  SimulationIssue,
  SimulationIssueCode,
} from "./simulation";
export {
  createInProcessWorkerFactory,
  createWorkerPlanningAdapter,
  createWorkerPlanningEndpoint,
  createWorkerPlanningRequest,
  DEFAULT_WORKER_PLANNING_PROGRESS_EVENTS,
  DEFAULT_WORKER_PLANNING_PROGRESS_INTERVAL_MS,
  MAX_WORKER_PLANNING_PROGRESS_EVENTS,
  WORKER_PLANNING_PROTOCOL_VERSION,
} from "./worker-planning";
export type {
  WorkerGeneratedClusterRegion,
  WorkerGenerationPayload,
  WorkerHierarchySource,
  WorkerHierarchicalClusterRegion,
  WorkerPlanningAdapter,
  WorkerPlanningAdapterOptions,
  WorkerPlanningCancelMessage,
  WorkerPlanningDiagnostic,
  WorkerPlanningDiagnosticCode,
  WorkerPlanningEndpoint,
  WorkerPlanningEndpointOptions,
  WorkerPlanningError,
  WorkerPlanningErrorCode,
  WorkerPlanningMessage,
  WorkerPlanningOperation,
  WorkerPlanningOperationResult,
  WorkerPlanningOutcome,
  WorkerPlanningPayload,
  WorkerPlanningPort,
  WorkerPlanningPortFactory,
  WorkerPlanningProgress,
  WorkerPlanningRefinementQuality,
  WorkerPlanningRequestMessage,
  WorkerPlanningRequestOptions,
  WorkerPlanningResponse,
  WorkerPlanningStage,
  WorkerPlanningSuccess,
  WorkerPlanningTask,
  WorkerPlanningTerminalResponse,
  WorkerRoutePlanningPayload,
  WorkerScenarioSource,
  WorkerRefinementPayload,
  WorkerPlanningProtocolErrorMessage,
} from "./worker-planning";
export {
  minimalScenario,
  multiLegJourneyRequest,
  multiLegJourneyScenario,
} from "./minimal-scenario";
export {
  DEFAULT_CLUSTER_GENERATOR_VERSION,
  SUPPORTED_CLUSTER_GENERATOR_VERSIONS,
  DEFAULT_CLUSTER_MATERIALIZED_SYSTEM_COUNT,
  DEFAULT_CLUSTER_REGION_RADIUS,
  DEFAULT_CLUSTER_ROUTE_HORIZON,
  DEFAULT_CLUSTER_ROUTE_MATERIALIZED_SYSTEMS,
  MAX_CLUSTER_MATERIALIZED_SYSTEM_COUNT,
  MAX_CLUSTER_ROUTE_CANDIDATES,
  MAX_CLUSTER_ROUTE_REFINEMENT_DEPTH,
  CLUSTER_REGION_BRANCHING_FACTOR,
  CLUSTER_REGION_LEAF_SYSTEM_CAPACITY,
  createHierarchicalCluster,
  generateClusterRegion,
  generateClusterScenario,
  generateHierarchicalCluster,
  generateRoutableClusterRegion,
  materializeClusterRegion,
  planClusterRoute,
  planGeneratedClusterRoute,
  planHierarchicalRoute,
} from "./cluster-generation";
export type {
  ClusterGenerationRequest,
  ClusterGenerationSeed,
  ClusterGenerationStatistics,
  ClusterRegionMaterializationRequest,
  ClusterRegionNode,
  ClusterRouteBounds,
  ClusterRoutePlanningFailure,
  ClusterRoutePlanningRequest,
  ClusterRoutePlanningResult,
  ClusterRoutePlanningSearchStats,
  ClusterRoutePlanningSuccess,
  ClusterRouteRefinementBudget,
  ClusterRouteRefinementReport,
  ClusterTopologyStatistics,
  GeneratedClusterRegion,
  HierarchicalClusterRegion,
} from "./cluster-generation";
